# Generated by Django 5.1.3 on 2024-11-19 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="useranswer",
            old_name="submitted_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="is_correct",
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
